sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t didac-wh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true didac-wh/docker-react npm run test

branches:
  only:
  - master
  