# branches:
#   only:
#   - master

sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t didac-wh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true didac-wh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: "Didac - Docker 1"
  env: "Didacdocker1-env"
  bucket_name: elasticbeanstalk-eu-west-1-906161076658
  bucket_path: "Didac - Docker 1"
  on:
    branch: master

  # For near future:
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY